[package]
name = "cranelift-symex"
version = "0.1.0"
authors = ["David Thien <dthien@eng.ucsd.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
